function WriteLeftMenu(divID, aID, divClassName, aClassName)
{
document.write("<div id=\"divID357\" class=\"headerLeftMenuInActive\"><a id=\"aID357\" href=\"#\" OnMouseOver=\"link('_dir','ExampleCode0',this)\" class=\"leftMenuLinkHeadInActive\">Example Code</a></div>\n");
document.write("<div id='leftmenutree' class='treeLeftMenu'>\n");
var treeLeftMenu = new TreeClass('treeLeftMenu', false);
treeLeftMenu.setTreeHeightDelta(-205);
treeLeftMenu.m_iDefaultExpandedLevel = 1;treeLeftMenu.setExpandCollapseNames('Expand All','Collapse All');
treeLeftMenu.startTree( true );
  treeLeftMenu.startParentNode('Help','"#"','','../../common/directoryBlue', { "onmouseover":"link('','../../index',this);" });
  treeLeftMenu.addNode('Compiling DoxyS','"#"','','../../common/page', { "onmouseover":"link('_page','../../CompilingDoxyS0',this);" });
  treeLeftMenu.addNode('Installing DoxyS','"#"','','../../common/page', { "onmouseover":"link('_page','../../InstallingDoxyS0',this);" });
  treeLeftMenu.addNode('Running DoxyS','"#"','','../../common/page', { "onmouseover":"link('_page','../../RunningDoxyS0',this);" });
  treeLeftMenu.startParentNode('Command Reference','"#"','','../../common/directoryBlue', { "onmouseover":"link('_dir','../Command_Reference/CommandReference0',this);" });
  treeLeftMenu.addNode('authorCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/authorCmd0',this);" });
  treeLeftMenu.addNode('briefCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/briefCmd0',this);" });
  treeLeftMenu.addNode('bugCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/bugCmd0',this);" });
  treeLeftMenu.addNode('callgraphCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/callgraphCmd0',this);" });
  treeLeftMenu.addNode('classCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/classCmd0',this);" });
  treeLeftMenu.addNode('codeCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/codeCmd0',this);" });
  treeLeftMenu.addNode('defCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/defCmd0',this);" });
  treeLeftMenu.addNode('defgroupCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/defgroupCmd0',this);" });
  treeLeftMenu.addNode('deprecatedCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/deprecatedCmd0',this);" });
  treeLeftMenu.addNode('dirCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/dirCmd0',this);" });
  treeLeftMenu.addNode('elseCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/elseCmd0',this);" });
  treeLeftMenu.addNode('elseifCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/elseifCmd0',this);" });
  treeLeftMenu.addNode('enumCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/enumCmd0',this);" });
  treeLeftMenu.addNode('EscapeSpecialCharsCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/EscapeSpecialCharsCmd0',this);" });
  treeLeftMenu.addNode('exampleCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/exampleCmd0',this);" });
  treeLeftMenu.addNode('examplesgroupCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/examplesgroupCmd0',this);" });
  treeLeftMenu.addNode('excludeCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/excludeCmd0',this);" });
  treeLeftMenu.addNode('fileCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/fileCmd0',this);" });
  treeLeftMenu.addNode('fnCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/fnCmd0',this);" });
  treeLeftMenu.addNode('ifCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/ifCmd0',this);" });
  treeLeftMenu.addNode('ifnotCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/ifnotCmd0',this);" });
  treeLeftMenu.addNode('imageCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/imageCmd0',this);" });
  treeLeftMenu.addNode('includeCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/includeCmd0',this);" });
  treeLeftMenu.addNode('ingroupCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/ingroupCmd0',this);" });
  treeLeftMenu.addNode('internalCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/internalCmd0',this);" });
  treeLeftMenu.addNode('inthisgroupCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/inthisgroupCmd0',this);" });
  treeLeftMenu.addNode('mainpageCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/mainpageCmd0',this);" });
  treeLeftMenu.addNode('namespaceCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/namespaceCmd0',this);" });
  treeLeftMenu.addNode('newlineCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/newlineCmd0',this);" });
  treeLeftMenu.addNode('noteCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/noteCmd0',this);" });
  treeLeftMenu.addNode('pageCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/pageCmd0',this);" });
  treeLeftMenu.addNode('paramCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/paramCmd0',this);" });
  treeLeftMenu.addNode('preCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/preCmd0',this);" });
  treeLeftMenu.addNode('remarkCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/remarkCmd0',this);" });
  treeLeftMenu.addNode('returnCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/returnCmd0',this);" });
  treeLeftMenu.addNode('saCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/saCmd0',this);" });
  treeLeftMenu.addNode('structCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/structCmd0',this);" });
  treeLeftMenu.addNode('throwCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/throwCmd0',this);" });
  treeLeftMenu.addNode('todoCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/todoCmd0',this);" });
  treeLeftMenu.addNode('typedefCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/typedefCmd0',this);" });
  treeLeftMenu.addNode('unionCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/unionCmd0',this);" });
  treeLeftMenu.addNode('unitCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/unitCmd0',this);" });
  treeLeftMenu.addNode('varCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/varCmd0',this);" });
  treeLeftMenu.addNode('versionCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/versionCmd0',this);" });
  treeLeftMenu.addNode('warningCmd','"#"','','../../common/page', { "onmouseover":"link('_page','../Command_Reference/warningCmd0',this);" });
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Config Options','"#"','','../../common/directoryBlue', { "onmouseover":"link('_dir','../Config_Options/ConfigOptions0',this);" });
  treeLeftMenu.addNode('DocParser','"#"','','../../common/page', { "onmouseover":"link('_page','../Config_Options/DocParser0',this);" });
  treeLeftMenu.addNode('DotOptions','"#"','','../../common/page', { "onmouseover":"link('_page','../Config_Options/DotOptions0',this);" });
  treeLeftMenu.addNode('FormulaLatexOptions','"#"','','../../common/page', { "onmouseover":"link('_page','../Config_Options/FormulaLatexOptions0',this);" });
  treeLeftMenu.addNode('GeneralOptions','"#"','','../../common/page', { "onmouseover":"link('_page','../Config_Options/GeneralOptions0',this);" });
  treeLeftMenu.addNode('Grouping','"#"','','../../common/page', { "onmouseover":"link('_page','../Config_Options/Grouping0',this);" });
  treeLeftMenu.addNode('HeaderAndFooter','"#"','','../../common/page', { "onmouseover":"link('_page','../Config_Options/HeaderAndFooter0',this);" });
  treeLeftMenu.addNode('IncludeInOutput','"#"','','../../common/page', { "onmouseover":"link('_page','../Config_Options/IncludeInOutput0',this);" });
  treeLeftMenu.addNode('InputOptions','"#"','','../../common/page', { "onmouseover":"link('_page','../Config_Options/InputOptions0',this);" });
  treeLeftMenu.addNode('Inputparsing','"#"','','../../common/page', { "onmouseover":"link('_page','../Config_Options/Inputparsing0',this);" });
  treeLeftMenu.addNode('LanguageOptions','"#"','','../../common/page', { "onmouseover":"link('_page','../Config_Options/LanguageOptions0',this);" });
  treeLeftMenu.addNode('LayoutHtml','"#"','','../../common/page', { "onmouseover":"link('_page','../Config_Options/LayoutHtml0',this);" });
  treeLeftMenu.addNode('LeftMenu','"#"','','../../common/page', { "onmouseover":"link('_page','../Config_Options/LeftMenu0',this);" });
  treeLeftMenu.addNode('MessagesOptions','"#"','','../../common/page', { "onmouseover":"link('_page','../Config_Options/MessagesOptions0',this);" });
  treeLeftMenu.addNode('OutputCustomization','"#"','','../../common/page', { "onmouseover":"link('_page','../Config_Options/OutputCustomization0',this);" });
  treeLeftMenu.addNode('PreprocessorOptions','"#"','','../../common/page', { "onmouseover":"link('_page','../Config_Options/PreprocessorOptions0',this);" });
  treeLeftMenu.addNode('SearchPageOptions','"#"','','../../common/page', { "onmouseover":"link('_page','../Config_Options/SearchPageOptions0',this);" });
  treeLeftMenu.addNode('Sorting','"#"','','../../common/page', { "onmouseover":"link('_page','../Config_Options/Sorting0',this);" });
  treeLeftMenu.addNode('SpecialOptions','"#"','','../../common/page', { "onmouseover":"link('_page','../Config_Options/SpecialOptions0',this);" });
  treeLeftMenu.addNode('Tabs','"#"','','../../common/page', { "onmouseover":"link('_page','../Config_Options/Tabs0',this);" });
  treeLeftMenu.addNode('Treeview','"#"','','../../common/page', { "onmouseover":"link('_page','../Config_Options/Treeview0',this);" });
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Documenting','"#"','','../../common/directoryBlue', { "onmouseover":"link('_dir','../Documenting/Documenting0',this);" });
  treeLeftMenu.addNode('Auto link generation','"#"','','../../common/page', { "onmouseover":"link('_page','../Documenting/Autolinkgeneration0',this);" });
  treeLeftMenu.addNode('Directories','"#"','','../../common/page', { "onmouseover":"link('_page','../Documenting/Directories0',this);" });
  treeLeftMenu.addNode('Documenting the code','"#"','','../../common/page', { "onmouseover":"link('_page','../Documenting/Documentingthecode0',this);" });
  treeLeftMenu.addNode('Excluding Input','"#"','','../../common/page', { "onmouseover":"link('_page','../Documenting/ExcludingInput0',this);" });
  treeLeftMenu.addNode('Formulas','"#"','','../../common/page', { "onmouseover":"link('_page','../Documenting/Formulas0',this);" });
  treeLeftMenu.addNode('Images','"#"','','../../common/page', { "onmouseover":"link('_page','../Documenting/Images0',this);" });
  treeLeftMenu.addNode('MainPage','"#"','','../../common/page', { "onmouseover":"link('_page','../Documenting/MainPage0',this);" });
  treeLeftMenu.addNode('Pages','"#"','','../../common/page', { "onmouseover":"link('_page','../Documenting/Pages0',this);" });
  treeLeftMenu.addNode('Special Sections','"#"','','../../common/page', { "onmouseover":"link('_page','../Documenting/SpecialSections0',this);" });
  treeLeftMenu.addNode('Text Formatting','"#"','','../../common/page', { "onmouseover":"link('_page','../Documenting/TextFormatting0',this);" });
  treeLeftMenu.addNode('Units','"#"','','../../common/page', { "onmouseover":"link('_page','../Documenting/Units0',this);" });
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Example Code','"#"','','../../common/directoryBlue', { "onmouseover":"link('_dir','ExampleCode0',this);" });
  treeLeftMenu.addNode('ClassInUnit','"#"','','../../common/class', { "onmouseover":"link('_class','ClassInUnit0',this);" });
  treeLeftMenu.addNode('HowToDocument','"#"','','../../common/class', { "onmouseover":"link('_class','HowToDocument0',this);" });
  treeLeftMenu.addNode('Overload','"#"','','../../common/class', { "onmouseover":"link('_class','Overload0',this);" });
  treeLeftMenu.addNode('Template<>','"#"','','../../common/class', { "onmouseover":"link('_class','Template23971',this);" });
  treeLeftMenu.addNode('Unit.h','"#"','','../../common/unit', { "onmouseover":"link('_unit','Unit_h0',this);" });
  treeLeftMenu.startParentNode('Inheritance','"#"','','../../common/directoryBlue', { "onmouseover":"link('_dir','Inheritance/Inheritance0',this);" });
  treeLeftMenu.addNode('BaseClass','"#"','','../../common/class', { "onmouseover":"link('_class','Inheritance/BaseClass0',this);" });
  treeLeftMenu.addNode('DerivedLevel_1','"#"','','../../common/class', { "onmouseover":"link('_class','Inheritance/DerivedLevel_10',this);" });
  treeLeftMenu.addNode('DerivedLevel_2','"#"','','../../common/class', { "onmouseover":"link('_class','Inheritance/DerivedLevel_20',this);" });
  treeLeftMenu.addNode('Final_1','"#"','','../../common/class', { "onmouseover":"link('_class','Inheritance/Final_10',this);" });
  treeLeftMenu.addNode('Final_2','"#"','','../../common/class', { "onmouseover":"link('_class','Inheritance/Final_20',this);" });
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Separate Docs','"#"','','../../common/directoryBlue', { "onmouseover":"link('_dir','Separate_Docs/SeparateDocs0',this);" });
  treeLeftMenu.addNode('NamespaceClass','"#"','','../../common/class', { "onmouseover":"link('_class','Separate_Docs/NamespaceClass5138',this);" });
  treeLeftMenu.addNode('SepDocClass','"#"','','../../common/class', { "onmouseover":"link('_class','Separate_Docs/SepDocClass0',this);" });
treeLeftMenu.endParentNode();
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Navigating In Doxygen','"#"','','../../common/directoryBlue', { "onmouseover":"link('_dir','../Navigating_In_Doxygen/NavigatingInDoxygen0',this);" });
  treeLeftMenu.addNode('AnonymousTypes','"#"','','../../common/page', { "onmouseover":"link('_page','../Navigating_In_Doxygen/AnonymousTypes0',this);" });
treeLeftMenu.endParentNode();
treeLeftMenu.endParentNode();
treeLeftMenu.endTree();
treeLeftMenu.readStateFromCookie();
document.write("</div>\n");
if(divID != "" && aID != "")
{
  var elemDiv = document.getElementById(divID);
  var elemA = document.getElementById(aID);
  if (elemDiv != undefined && elemA != undefined ) { // this is needed to abvoid crashing js on some memberpages 
    elemDiv.className = divClassName;
    elemA.className = aClassName;
  }
}
}
