function WriteLeftMenu(divID, aID, divClassName, aClassName)
{
document.write("<div id=\"divID175\" class=\"headerLeftMenuInActive\"><a id=\"aID175\" href=\"#\" OnMouseOver=\"link('_statsindex','index',this)\" class=\"leftMenuLinkHeadInActive\">Statistics</a></div>\n");
document.write("<div id='leftmenutree' class='treeLeftMenu'>\n");
var treeLeftMenu = new TreeClass('treeLeftMenu', false);
treeLeftMenu.setTreeHeightDelta(-205);
treeLeftMenu.m_iDefaultExpandedLevel = 1;treeLeftMenu.setExpandCollapseNames('Expand All','Collapse All');
treeLeftMenu.startTree( true );
  treeLeftMenu.startParentNode('Help','"#"','','../directoryBlue', { "onmouseover":"link('','../../index',this);" });
  treeLeftMenu.addNode('Compiling DoxyS','"#"','','../page', { "onmouseover":"link('_page','../../CompilingDoxyS0',this);" });
  treeLeftMenu.addNode('Installing DoxyS','"#"','','../page', { "onmouseover":"link('_page','../../InstallingDoxyS0',this);" });
  treeLeftMenu.addNode('Running DoxyS','"#"','','../page', { "onmouseover":"link('_page','../../RunningDoxyS0',this);" });
  treeLeftMenu.startParentNode('Command Reference','"#"','','../directoryBlue', { "onmouseover":"link('_dir','../../helpsrc/Command_Reference/CommandReference0',this);" });
  treeLeftMenu.addNode('authorCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/authorCmd0',this);" });
  treeLeftMenu.addNode('briefCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/briefCmd0',this);" });
  treeLeftMenu.addNode('bugCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/bugCmd0',this);" });
  treeLeftMenu.addNode('callgraphCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/callgraphCmd0',this);" });
  treeLeftMenu.addNode('classCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/classCmd0',this);" });
  treeLeftMenu.addNode('codeCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/codeCmd0',this);" });
  treeLeftMenu.addNode('defCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/defCmd0',this);" });
  treeLeftMenu.addNode('defgroupCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/defgroupCmd0',this);" });
  treeLeftMenu.addNode('deprecatedCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/deprecatedCmd0',this);" });
  treeLeftMenu.addNode('dirCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/dirCmd0',this);" });
  treeLeftMenu.addNode('elseCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/elseCmd0',this);" });
  treeLeftMenu.addNode('elseifCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/elseifCmd0',this);" });
  treeLeftMenu.addNode('enumCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/enumCmd0',this);" });
  treeLeftMenu.addNode('EscapeSpecialCharsCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/EscapeSpecialCharsCmd0',this);" });
  treeLeftMenu.addNode('exampleCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/exampleCmd0',this);" });
  treeLeftMenu.addNode('examplesgroupCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/examplesgroupCmd0',this);" });
  treeLeftMenu.addNode('excludeCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/excludeCmd0',this);" });
  treeLeftMenu.addNode('fileCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/fileCmd0',this);" });
  treeLeftMenu.addNode('fnCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/fnCmd0',this);" });
  treeLeftMenu.addNode('ifCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/ifCmd0',this);" });
  treeLeftMenu.addNode('ifnotCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/ifnotCmd0',this);" });
  treeLeftMenu.addNode('imageCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/imageCmd0',this);" });
  treeLeftMenu.addNode('includeCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/includeCmd0',this);" });
  treeLeftMenu.addNode('ingroupCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/ingroupCmd0',this);" });
  treeLeftMenu.addNode('internalCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/internalCmd0',this);" });
  treeLeftMenu.addNode('inthisgroupCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/inthisgroupCmd0',this);" });
  treeLeftMenu.addNode('mainpageCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/mainpageCmd0',this);" });
  treeLeftMenu.addNode('namespaceCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/namespaceCmd0',this);" });
  treeLeftMenu.addNode('newlineCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/newlineCmd0',this);" });
  treeLeftMenu.addNode('noteCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/noteCmd0',this);" });
  treeLeftMenu.addNode('pageCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/pageCmd0',this);" });
  treeLeftMenu.addNode('paramCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/paramCmd0',this);" });
  treeLeftMenu.addNode('preCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/preCmd0',this);" });
  treeLeftMenu.addNode('remarkCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/remarkCmd0',this);" });
  treeLeftMenu.addNode('returnCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/returnCmd0',this);" });
  treeLeftMenu.addNode('saCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/saCmd0',this);" });
  treeLeftMenu.addNode('structCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/structCmd0',this);" });
  treeLeftMenu.addNode('throwCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/throwCmd0',this);" });
  treeLeftMenu.addNode('todoCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/todoCmd0',this);" });
  treeLeftMenu.addNode('typedefCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/typedefCmd0',this);" });
  treeLeftMenu.addNode('unionCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/unionCmd0',this);" });
  treeLeftMenu.addNode('unitCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/unitCmd0',this);" });
  treeLeftMenu.addNode('varCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/varCmd0',this);" });
  treeLeftMenu.addNode('versionCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/versionCmd0',this);" });
  treeLeftMenu.addNode('warningCmd','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Command_Reference/warningCmd0',this);" });
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Config Options','"#"','','../directoryBlue', { "onmouseover":"link('_dir','../../helpsrc/Config_Options/ConfigOptions0',this);" });
  treeLeftMenu.addNode('DocParser','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Config_Options/DocParser0',this);" });
  treeLeftMenu.addNode('DotOptions','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Config_Options/DotOptions0',this);" });
  treeLeftMenu.addNode('FormulaLatexOptions','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Config_Options/FormulaLatexOptions0',this);" });
  treeLeftMenu.addNode('GeneralOptions','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Config_Options/GeneralOptions0',this);" });
  treeLeftMenu.addNode('Grouping','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Config_Options/Grouping0',this);" });
  treeLeftMenu.addNode('HeaderAndFooter','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Config_Options/HeaderAndFooter0',this);" });
  treeLeftMenu.addNode('IncludeInOutput','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Config_Options/IncludeInOutput0',this);" });
  treeLeftMenu.addNode('InputOptions','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Config_Options/InputOptions0',this);" });
  treeLeftMenu.addNode('Inputparsing','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Config_Options/Inputparsing0',this);" });
  treeLeftMenu.addNode('LanguageOptions','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Config_Options/LanguageOptions0',this);" });
  treeLeftMenu.addNode('LayoutHtml','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Config_Options/LayoutHtml0',this);" });
  treeLeftMenu.addNode('LeftMenu','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Config_Options/LeftMenu0',this);" });
  treeLeftMenu.addNode('MessagesOptions','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Config_Options/MessagesOptions0',this);" });
  treeLeftMenu.addNode('OutputCustomization','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Config_Options/OutputCustomization0',this);" });
  treeLeftMenu.addNode('PreprocessorOptions','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Config_Options/PreprocessorOptions0',this);" });
  treeLeftMenu.addNode('SearchPageOptions','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Config_Options/SearchPageOptions0',this);" });
  treeLeftMenu.addNode('Sorting','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Config_Options/Sorting0',this);" });
  treeLeftMenu.addNode('SpecialOptions','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Config_Options/SpecialOptions0',this);" });
  treeLeftMenu.addNode('Tabs','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Config_Options/Tabs0',this);" });
  treeLeftMenu.addNode('Treeview','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Config_Options/Treeview0',this);" });
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Documenting','"#"','','../directoryBlue', { "onmouseover":"link('_dir','../../helpsrc/Documenting/Documenting0',this);" });
  treeLeftMenu.addNode('Auto link generation','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Documenting/Autolinkgeneration0',this);" });
  treeLeftMenu.addNode('Directories','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Documenting/Directories0',this);" });
  treeLeftMenu.addNode('Documenting the code','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Documenting/Documentingthecode0',this);" });
  treeLeftMenu.addNode('Excluding Input','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Documenting/ExcludingInput0',this);" });
  treeLeftMenu.addNode('Formulas','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Documenting/Formulas0',this);" });
  treeLeftMenu.addNode('Images','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Documenting/Images0',this);" });
  treeLeftMenu.addNode('MainPage','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Documenting/MainPage0',this);" });
  treeLeftMenu.addNode('Pages','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Documenting/Pages0',this);" });
  treeLeftMenu.addNode('Special Sections','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Documenting/SpecialSections0',this);" });
  treeLeftMenu.addNode('Text Formatting','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Documenting/TextFormatting0',this);" });
  treeLeftMenu.addNode('Units','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Documenting/Units0',this);" });
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Example Code','"#"','','../directoryBlue', { "onmouseover":"link('_dir','../../helpsrc/Example_Code/ExampleCode0',this);" });
  treeLeftMenu.addNode('ClassInUnit','"#"','','../class', { "onmouseover":"link('_class','../../helpsrc/Example_Code/ClassInUnit0',this);" });
  treeLeftMenu.addNode('HowToDocument','"#"','','../class', { "onmouseover":"link('_class','../../helpsrc/Example_Code/HowToDocument0',this);" });
  treeLeftMenu.addNode('Overload','"#"','','../class', { "onmouseover":"link('_class','../../helpsrc/Example_Code/Overload0',this);" });
  treeLeftMenu.addNode('Template<>','"#"','','../class', { "onmouseover":"link('_class','../../helpsrc/Example_Code/Template23971',this);" });
  treeLeftMenu.addNode('Unit.h','"#"','','../unit', { "onmouseover":"link('_unit','../../helpsrc/Example_Code/Unit_h0',this);" });
  treeLeftMenu.startParentNode('Inheritance','"#"','','../directoryBlue', { "onmouseover":"link('_dir','../../helpsrc/Example_Code/Inheritance/Inheritance0',this);" });
  treeLeftMenu.addNode('BaseClass','"#"','','../class', { "onmouseover":"link('_class','../../helpsrc/Example_Code/Inheritance/BaseClass0',this);" });
  treeLeftMenu.addNode('DerivedLevel_1','"#"','','../class', { "onmouseover":"link('_class','../../helpsrc/Example_Code/Inheritance/DerivedLevel_10',this);" });
  treeLeftMenu.addNode('DerivedLevel_2','"#"','','../class', { "onmouseover":"link('_class','../../helpsrc/Example_Code/Inheritance/DerivedLevel_20',this);" });
  treeLeftMenu.addNode('Final_1','"#"','','../class', { "onmouseover":"link('_class','../../helpsrc/Example_Code/Inheritance/Final_10',this);" });
  treeLeftMenu.addNode('Final_2','"#"','','../class', { "onmouseover":"link('_class','../../helpsrc/Example_Code/Inheritance/Final_20',this);" });
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Separate Docs','"#"','','../directoryBlue', { "onmouseover":"link('_dir','../../helpsrc/Example_Code/Separate_Docs/SeparateDocs0',this);" });
  treeLeftMenu.addNode('NamespaceClass','"#"','','../class', { "onmouseover":"link('_class','../../helpsrc/Example_Code/Separate_Docs/NamespaceClass5138',this);" });
  treeLeftMenu.addNode('SepDocClass','"#"','','../class', { "onmouseover":"link('_class','../../helpsrc/Example_Code/Separate_Docs/SepDocClass0',this);" });
treeLeftMenu.endParentNode();
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Navigating In Doxygen','"#"','','../directoryBlue', { "onmouseover":"link('_dir','../../helpsrc/Navigating_In_Doxygen/NavigatingInDoxygen0',this);" });
  treeLeftMenu.addNode('AnonymousTypes','"#"','','../page', { "onmouseover":"link('_page','../../helpsrc/Navigating_In_Doxygen/AnonymousTypes0',this);" });
treeLeftMenu.endParentNode();
treeLeftMenu.endParentNode();
treeLeftMenu.endTree();
treeLeftMenu.readStateFromCookie();
document.write("</div>\n");
document.write("<div class=\"paragraphLeftMenu\">Pages</div>\n");
document.write("<div id=\"divID368\" class=\"leftMenuTreeInActive\"><a id=\"aID368\" href=\"#\" OnMouseOver=\"link('_statsgeneral','stats_general',this)\" class=\"leftMenuLinkInActive\">General</a></div>\n");
document.write("<div id=\"divID369\" class=\"leftMenuTreeInActive\"><a id=\"aID369\" href=\"#\" OnMouseOver=\"link('_statsundoc','stats_undoc',this)\" class=\"leftMenuLinkInActive\">Undocumented</a></div>\n");
document.write("<div id=\"divID370\" class=\"leftMenuTreeInActive\"><a id=\"aID370\" href=\"#\" OnMouseOver=\"link('_statsmsg','stats_msg_msg',this)\" class=\"leftMenuLinkInActive\">Msg-Messages</a></div>\n");
document.write("<div id=\"divID371\" class=\"leftMenuTreeInActive\"><a id=\"aID371\" href=\"#\" OnMouseOver=\"link('_statsmsg','stats_msg_warn',this)\" class=\"leftMenuLinkInActive\">Msg-Warnings</a></div>\n");
document.write("<div id=\"divID372\" class=\"leftMenuTreeInActive\"><a id=\"aID372\" href=\"#\" OnMouseOver=\"link('_statsmsg','stats_msg_err',this)\" class=\"leftMenuLinkInActive\">Msg-Errors</a></div>\n");
document.write("<div id=\"divID373\" class=\"leftMenuTreeInActive\"><a id=\"aID373\" href=\"#\" OnMouseOver=\"link('_statsmsg','stats_msg_dbg',this)\" class=\"leftMenuLinkInActive\">Msg-Debug</a></div>\n");
if(divID != "" && aID != "")
{
  var elemDiv = document.getElementById(divID);
  var elemA = document.getElementById(aID);
  if (elemDiv != undefined && elemA != undefined ) { // this is needed to abvoid crashing js on some memberpages 
    elemDiv.className = divClassName;
    elemA.className = aClassName;
  }
}
}
